# Generated by Django 5.1.1 on 2024-09-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_seller',
        ),
    ]
